### PR TITLE
chore: update dependencies for design tokens

### PR DESCRIPTION
**Pull request by PKulkoRaccoonGang**
This pull request includes a change to the `package.json` file to update the dependency for `@edx/frontend-component-footer`. The change switches from a versioned dependency to a GitHub repository reference.

Dependency update:

* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L42-R42): Changed the `@edx/frontend-component-footer` dependency to point to a specific branch in a GitHub repository (`github:PKulkoRaccoonGang/frontend-component-footer#Peter_Kulko/support-design-tokens`).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @PKulkoRaccoonGang! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @PKulkoRaccoonGang! Just checking to see if you plan to pursue this PR?

**Comment by mphilbrick211** [comment]
Hi @PKulkoRaccoonGang - can this be closed?

**Comment by PKulkoRaccoonGang** [comment]
@mphilbrick211 Closed, thank you!

**Pull request closed without merging**
